const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{deneyIndex: 0},
	{siviOn: 0},
	{posY: 0},
	{elementBar: 0},
	{isSivi: 0},
	{tintIndex: 0},
	{cVal: 0},
	{siviOpacity: 0},
	{maxLimit: 0},
	{minLimit: 0},
	{materialBtn: 0},
	{basınçdeğer: 0},
	{basincText: 0},
	{küçükboskutu: 0},
	{gosterge: 0},
	{siviTitle: 0},
	{siviMiktarText: 0},
	{masa: 0},
	{verticalSliderEmpty: 0},
	{verticalSliderFill: 0},
	{DragDrop: 0},
	{verticalSliderBtn: 0},
	{beherust: 0},
	{siviArka: 0},
	{beherarka: 0},
	{sehba: 0},
	{termmometre: 0},
	{fire: 0},
	{destek: 0},
	{fireCountBtn: 0},
	{gösterge: 0},
	{playDeneyBtn: 0},
	{sicaklikText: 0},
	{timeBg: 0},
	{timeText1: 0},
	{timeText2: 0},
	{deneyBtn: 0},
	{kati: 0},
	{suzgec: 0},
	{activeDeneyIndex: 0},
	{sicaklikValue1: 0},
	{sicaklikValue2: 0},
	{isActiveMaterial1Sivi: 0},
	{isActiveMaterial2Sivi: 0},
	{activeCVal1: 0},
	{activeGrVal1: 0},
	{increment1: 0},
	{increment2: 0},
	{activeCVal2: 0},
	{activeGrVal2: 0},
	{activeMaterialIndex1: 0},
	{activeMaterialIndex2: 0},
	{fireCountDeney1: 0},
	{fireCountDeney2: 0},
	{deney1TimeStart: 0},
	{deney1TimeCount: 0},
	{deney2TimeStart: 0},
	{deney2TimeCount: 0},
	{activeMinLimit1: 0},
	{ActiveMaxLimit1: 0},
	{activeMinLimit2: 0},
	{ActiveMaxLimit2: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	siviOn: class extends self.ISpriteInstance {},
	elementBar: class extends self.ISpriteInstance {},
	materialBtn: class extends self.ISpriteInstance {},
	basınçdeğer: class extends self.ISpriteInstance {},
	basincText: class extends self.ITextInstance {},
	küçükboskutu: class extends self.ISpriteInstance {},
	gosterge: class extends self.ISpriteInstance {},
	siviTitle: class extends self.ITextInstance {},
	siviMiktarText: class extends self.ITextInstance {},
	masa: class extends self.ISpriteInstance {},
	verticalSliderEmpty: class extends self.ISpriteInstance {},
	verticalSliderFill: class extends self.ISpriteInstance {},
	verticalSliderBtn: class extends self.ISpriteInstance {},
	beherust: class extends self.ISpriteInstance {},
	siviArka: class extends self.ISpriteInstance {},
	beherarka: class extends self.ISpriteInstance {},
	sehba: class extends self.ISpriteInstance {},
	termmometre: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	destek: class extends self.ISpriteInstance {},
	fireCountBtn: class extends self.ISpriteInstance {},
	gösterge: class extends self.ISpriteInstance {},
	playDeneyBtn: class extends self.ISpriteInstance {},
	sicaklikText: class extends self.ITextInstance {},
	timeBg: class extends self.ISpriteInstance {},
	timeText1: class extends self.ITextInstance {},
	timeText2: class extends self.ITextInstance {},
	deneyBtn: class extends self.ISpriteInstance {},
	kati: class extends self.ISpriteInstance {},
	suzgec: class extends self.ISpriteInstance {}
}